abbreviations:
  attribute: "attr"
  property:  "prop"
  string:    "str"

# Taken from Tavis Rudd's alphabet.txt and PyCon talk
# https://gist.github.com/tavisrudd/5361092
# https://www.youtube.com/watch?v=8SkdfdXWYaI
static:
  aff    : "a"
  brav   : "b"
  bravo  : "b"
  cai    : "c"
  doy    : "d"
  delt   : "d"
  delta  : "d"
  eck    : "e"
  echo   : "e"
  fay    : "f"
  goff   : "g"
  hoop   : "h"
  ish    : "i"
  jo     : "j"
  keel   : "k"
  lee    : "l"
  lima   : "l"
  mike   : "m"
  noy    : "n"
  osc    : "o"
  osh    : "o"
  pui    : "p"
  pom    : "p"
  quebec : "q"
  queen  : "q"
  ree    : "r"
  soi    : "s"
  tay    : "t"
  uni    : "u"
  umm    : "u"
  van    : "v"
  wes    : "w"
  xanth  : "x"
  yaa    : "y"
  zul    : "z"
  zulu   : "z"

  slap   : "<enter>"
  laip   : "("
  raip   : ")"
  lace   : "("
  race   : ")"
  lack   : "["
  rack   : "]"
